### PR TITLE
Add notes for how to do a kernel bisect

### PR DESCRIPTION
**Pull request by dustymabe**

### CODE REVIEW

**Comment by miabbott** [comment]
This is great information...how do we make it more discoverable?  i.e.  where should we link from to make this easier for devs/users to find this?

**Comment by dustymabe** [comment]
I really am not sure. I wasn't sure of a good place for this so I asked and this location was suggested.

**Comment by miabbott** [comment]
> I really am not sure. I wasn't sure of a good place for this so I asked and this location was suggested.

Nothing to block on, but something to try and improve in the future.

**Review by jlebon — APPROVED** [review]
Nice, this is very useful.

**Pull request merged**
