### PR TITLE
add minutes from FCOS community sessions

### PR DESCRIPTION
**Pull request by miabbott**
During the CoreOS Virtual F2F, we held two sessions open to the
community to discuss:

  - Growing the Fedora CoreOS Community
  - Making Fedora CoreOS an Official Fedora Edition

This captures the HackMD contents from those two sessions.

### CODE REVIEW

**Comment by miabbott** [comment]
I have the recordings too; not sure the best place to store those

**Review by jlebon — APPROVED** [review]
Good idea, thanks Micah!

**Comment by jlebon** [comment]
> I have the video recordings too; not sure the best place to store those

Would it be possible to host it on Google Drive and link to it from these docs?

**Comment by miabbott** [comment]
> > I have the video recordings too; not sure the best place to store those
> 
> Would it be possible to host it on Google Drive and link to it from these docs?

Turns out @cverna is working on uploading the videos to the Fedora YouTube channel;  we can update these with links when they are available

**Comment by cverna** [comment]
Pushed a commit with the recording links

**Pull request merged**
