### PR TITLE
Add ROADMAP.md - schedule for first Fedora CoreOS release

### PR DESCRIPTION
**Pull request by dustymabe**

### CODE REVIEW

**Comment by dustymabe** [comment]
cc @jlebon @ajeddeloh @bgilbert @arithx @cgwalters @lucab @sinnykumari 

There is a lot that is still missing from the roadmap, but this is a start

**Comment by sinnykumari** [comment]
One item I can think of:
* M Finalize automatic rollback strategy https://github.com/coreos/fedora-coreos-tracker/issues/47

Maybe also include migration doc from FAH to FCOS?

**Comment by sinnykumari** [comment]
LGTM

**Comment by dustymabe** [comment]
going to merge this. will continually make updates to it as we go

**Pull request merged**
