### PR TITLE
design: add Packet section to cloud agents

### PR DESCRIPTION
**Pull request by dustymabe**

### CODE REVIEW

**Comment by dustymabe** [comment]
thanks @arithx - just rebased on top of latest master. will wait for @bgilbert to review before merge

**Comment by vielmetti** [comment]
In the design doc, you should link to the Packet doc for the grub console string (which also has to specific 115200 as the bit rate). Also, it's worth noting for arm64 support that the Packet grub console setup for arm64 is ever so slightly different. I'll post the exact Packet docs in a moment.

**Comment by dustymabe** [comment]
hey @vielmetti, thanks! If you can link us to those docs we will use them when we develop the actual snippets that alter the kernel CLI. 

For the design doc I think the point is just that "we'll need some packet specific kernel args".

**Comment by dustymabe** [comment]
i talked to @bgilbert and he already has a draft adding the packet info to the design doc (oops). I'll close this out in favor of his PR that he'll open shortly.

**Pull request closed without merging**
