### PR TITLE
internals: Talk about multipath

### PR DESCRIPTION
**Pull request by cgwalters**
Let's collate information on this.

### CODE REVIEW

**Comment by cgwalters** [comment]
One thing I don't understand at all here is `root=/dev/disk/by-label/dm-mpath-root`.  I don't see such a symlink in the real root at least.  Do the udev rules only run in the initramfs?

Another discovery here was that in recent systemd (not in rhel8) there's a new synthetic `blockdev@<device>.target` which generated mount units from the stock mount generator depend on.  This acts as a convenient "hook all setup for this device" unit and it'd seem to make sense to use it for multipath.  I guess we could just "backport" it to rhel8 easily enough though.

**Comment by cgwalters** [comment]
Actually yet another wrinkle in all of this is that in CoreOS we want to mount `/boot` in the initramfs on firstboot for Ignition, which is not necessary on non-Ignition systems usually.  Except for FIPS which also wants to mount `/boot`.

But in our current flow of "boot non-multipath, configure then reboot", we don't need to deal with mpath for `/boot` in the initramfs.

**Comment by jlebon** [comment]
Did you see https://github.com/coreos/fedora-coreos-config/pull/1011? This will significantly change how we interact with multipath and should fix races between `multipathd` and other things trying to use e.g. `/boot`.

**Comment by cgwalters** [comment]
Ah...I hadn't and I didn't know you were working on a mpath-related bz too.

**Comment by jlebon** [comment]
Ahh OK, and you're looking at https://bugzilla.redhat.com/show_bug.cgi?id=1944660, right?

So ughhh, I think there we'll need to do something similar to https://github.com/coreos/fedora-coreos-config/pull/1011 but in the real root, where the boot generator dynamically changes the device to mount based on `rd.multipath` to be the `dm-mpath-boot` symlink instead. Then systemd will know to wait for it to show up.

**Comment by darkmuggle** [comment]
> One thing I don't understand at all here is `root=/dev/disk/by-label/dm-mpath-root`. I don't see such a symlink in the real root at least. Do the udev rules only run in the initramfs?

https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/05core/usr/lib/udev/rules.d/90-coreos-device-mapper.rules

These rules are CoreOS specific since there is no by-label link create for Multipath devices. I create the rule based on the other multipath targets that create symlinked for multipath devices. If you don't see those links in the real root, that's because multipath is not active on the system.

**Comment by cgwalters** [comment]
I've got a shell in an rhcos-4.8 system running with `--qemu-multipath` and applied the kargs from https://github.com/coreos/coreos-assembler/blob/60f675ec5037b84c01f17192d773a14166dc6a14/mantle/kola/tests/misc/multipath.go#L57 and multipath certainly looks active:

```
[root@cosa-devsh ~]# lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
sda           8:0    0   16G  0 disk  
`-mpatha    253:0    0   16G  0 mpath 
  |-mpatha1 253:1    0    1M  0 part  
  |-mpatha2 253:2    0  127M  0 part  
  |-mpatha3 253:3    0  384M  0 part  /boot
  `-mpatha4 253:4    0 15.5G  0 part  /sysroot
sdb           8:16   0   16G  0 disk  
`-mpatha    253:0    0   16G  0 mpath 
  |-mpatha1 253:1    0    1M  0 part  
  |-mpatha2 253:2    0  127M  0 part  
  |-mpatha3 253:3    0  384M  0 part  /boot
  `-mpatha4 253:4    0 15.5G  0 part  /sysroot
[root@cosa-devsh ~]# findmnt /
TARGET SOURCE                                                                                                              FSTYPE OPTIONS
/      /dev/mapper/mpatha4[/ostree/deploy/rhcos/deploy/1dfb50d9fd2fa0fa9269827a443109b031f9e51dcdd169def9c800d31fffffd4.1] xfs    rw,relatime,seclabel,attr2,inode64,logbufs=8,logbsize=32k,prjquota
[root@cosa-devsh ~]# findmnt /boot
TARGET SOURCE              FSTYPE OPTIONS
/boot  /dev/mapper/mpatha3 ext4   ro,nosuid,nodev,relatime,seclabel
[root@cosa-devsh ~]# 
```

But:
```
[root@cosa-devsh ~]# ls -al /dev/disk/by-label/
total 0
drwxr-xr-x. 2 root root 100 May 14 14:31 .
drwxr-xr-x. 8 root root 160 May 14 14:31 ..
lrwxrwxrwx. 1 root root  10 May 14 14:31 EFI-SYSTEM -> ../../dm-2
lrwxrwxrwx. 1 root root  10 May 14 14:31 boot -> ../../dm-3
lrwxrwxrwx. 1 root root  10 May 14 14:31 root -> ../../dm-4
[root@cosa-devsh ~]# 
```

**Comment by jlebon** [comment]
Yeah, what I've found while hacking on https://github.com/coreos/fedora-coreos-config/pull/1011 was that the symlinks are quite flaky (though this was in the initrd). E.g. the `wipefs` in `ignition-ostree-growfs` causes the symlinks to get lost even though it's not at all (or at least shouldn't be) touching the XFS superblock. What I think is happening there (and in general elsewhere) is that the symlinks get lost whenever a `BLKRRPART` is issued. This is why I added a `udevadm trigger --settle` there to get the symlinks back. Mind you, this doesn't prevent multipath to work just fine still, because the device mapper targets themselves aren't flaky. But still, we should dig more into this.

**Comment by cgwalters** [comment]
Right, I think anything changing the partition table is going to retrigger the whole udev stack.

**Comment by cgwalters** [comment]
Anyways though, any objections to merging this as is since it documents current reality?

**Pull request merged**
