### PR TITLE
roadmap: add timeline for Ignition spec 3.0.0

### PR DESCRIPTION
**Pull request by ajeddeloh**

### CODE REVIEW

**Comment by dustymabe** [comment]
any chance you could link to an existing ticket like is done for the other roadmap entries ?

**Comment by ajeddeloh** [comment]
There isn't a specific tracker ticket for this. The closest is the one saying "we'll break compat with the 2.x spec", which doesn't fit. I also don't think it makes sense to track the Ignition work here (Ignition has it's own tracker). I could link to the 3.x milestone in the Ignition repo if we want to go cross-repo.

**Comment by dustymabe** [comment]
> I could link to the 3.x milestone in the Ignition repo if we want to go cross-repo.

I'd say that is better than nothing. We already have at least one link in the roadmap to coreos-metadata repo I think.. and we'll probably have more in the future.

**Comment by ajeddeloh** [comment]
Updated with link to the Ignition milestone

**Comment by dustymabe** [comment]
ok with the link things LGTM.. so I think we can merge. will get a second opinion from @bgilbert

**Pull request merged**
