### PR TITLE
release-notes: Initial import for all streams

### PR DESCRIPTION
**Pull request by travier**
Import a set of JSON files that list issues fixed in a given Fedora CoreOS release.

This list will be displayed as part of the release notes at https://getfedora.org/en/coreos

See: https://github.com/coreos/fedora-coreos-tracker/issues/194

### CODE REVIEW

**Comment by dustymabe** [comment]
Looks great! Would we ever hand edit these files? If so maybe we'd want to use yaml instead?

**Review by dustymabe — APPROVED** [review]

**Comment by jlebon** [comment]
WDYT about having this in https://github.com/coreos/fedora-coreos-streams instead? That's where new version IDs referenced in these files are blessed and pushed out. We also have some automation there that could in the future roll this up as part of the rollout PR, but we could start doing it manually for now of course. Also, we already have a job that syncs things there to S3 that we can easily tweak.

And thanks a lot for working on this!

**Comment by bgilbert** [comment]
fedora-coreos-streams requires two approvals to merge, which already makes it somewhat painful to update the ancillary bits in that repo.  For that reason alone I'd be inclined to avoid.  There's also some merit to keeping the release notes in the same repo as the bug tracker.

**Comment by travier** [comment]
Syncing to S3 would be nice indeed. I don't have a preference on where to host this but I think we should keep the overhead of updating this file low. We can also move it to another place latter if needed.

**Comment by travier** [comment]
Thinking about this more, making the release notes a part of the release process would make sense (independently from the place where they are stored).

**Comment by travier** [comment]
Closing in favor of https://github.com/coreos/fedora-coreos-streams/pull/477

**Pull request closed without merging**
